# Generated by Django 3.2.12 on 2022-05-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="scan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sku", models.CharField(max_length=100)),
                ("origin", models.CharField(max_length=100)),
                ("change", models.CharField(max_length=100)),
            ],
        ),
    ]
