# Generated by Django 3.2.12 on 2022-05-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scans", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scan",
            name="origin",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
