# Generated by Django 3.2.12 on 2022-05-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0003_scan_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='change',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
