# Generated by Django 3.2.12 on 2022-06-27 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scans", "0004_alter_scan_change"),
    ]

    operations = [
        migrations.RenameField(
            model_name="scan",
            old_name="change",
            new_name="last_location",
        ),
        migrations.RenameField(
            model_name="scan",
            old_name="origin",
            new_name="location_now",
        ),
    ]
