# Generated by Django 3.2.12 on 2022-06-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0006_auto_20220630_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='scan_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
