# Generated by Django 3.2.12 on 2022-07-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0008_alter_scan_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='tracking',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
