# Generated by Django 3.2.12 on 2022-12-29 21:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0010_alter_scan_scan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='scan_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
